Package.describe({
  name: "jmsalash:chartjs",
  summary: "Chart.js v2.0-beta for Meteor",
  version: "0.1.6",
  git: "https://github.com/jmsalash/meteor-chartjs"
});

Package.onUse(function(api) {
  // Meteor releases below this version are not supported
  api.versionsFrom("1.2.0.1");

  // Core packages and 3rd party packages
  api.use("momentjs:moment@2.10.6");	
  
  // The files of this package
  api.addFiles("client/Chart.js", ["client"]);

  // The variables that become global for users of your package
  //api.export("Chart", ["client"]);
  api.export("", ["client"]);
});



Package.onTest(function (api) {
  api.use("momentjs:moment@2.10.6");
  api.use("sanjo:jasmine@0.21.0");	
  api.use("jmsalash:chartjs");
  api.addFiles("tests/jasmine/client/integration/mockContext.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/controller.bar.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/controller.doughnut.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/controller.line.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/core.element.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/core.helpers.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/core.layoutService.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/element.arc.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/element.line.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/element.point.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/element.rectangle.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/scale.category.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/scale.linear.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/scale.logarithmic.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/scale.radialLinear.tests.js", ["client"]);
  api.addFiles("tests/jasmine/client/integration/scale.time.tests.js", ["client"]);
});

/* Generated by okgrow:package-kitchen */
